#ifndef NOTES_H
#define NOTES_H

static const char * const notes[] =
{
	"Ammunition Codes",
	"Maxes your missile count.\n\nPress the L button to execute this code.",
	"Keeps your missile count maxed.",
	"Keeps your bubbline ammo maxed.",
	"Keeps your machine gun ammo maxed.",
	"Health Codes",
	"Maxes your health.\n\nPress the R button to execute this code.",
	"Keeps your health maxed at 255.",
	"Weapon Charge Codes",
	"All Codes\n\nExcludes Blade and Nemesis",
	"Maintains lvl3 charge on all weapons.\n\nExcludes Blade and Nemesis.",
	"Maintains lvl2 charge on all weapons.\n\nExcludes Blade and Nemesis.",
	"Maintains lvl1 charge on all weapons.\n\nExcludes Blade and Nemesis.",
	"Blade Codes",
	"Maintains max charge on the blade.",
	"Maintains lvl3 charge on the blade.",
	"Maintains lvl2 charge on the blade.",
	"Maintains lvl1 charge on the blade.",
	"Bubbline Codes",
	"Maintains max charge on the bubbline.",
	"Maintains lvl3 charge on the bubbline.",
	"Maintains lvl2 charge on the bubbline.",
	"Maintains lvl1 charge on the bubbline.",
	"Fireball Codes",
	"Maintains max charge on the fireball.",
	"Maintains lvl3 charge on the fireball.",
	"Maintains lvl2 charge on the fireball.",
	"Maintains lvl1 charge on the fireball.",
	"Machine Gun Codes",
	"Maintains max charge on the machine gun.",
	"Maintains lvl3 charge on the machine gun.",
	"Maintains lvl2 charge on the machine gun.",
	"Maintains lvl1 charge on the machine gun.",
	"Missile Launcher Codes",
	"Maintains max charge on the missile launcher.",
	"Maintains lvl3 charge on the missile launcher.",
	"Maintains lvl2 charge on the missile launcher.",
	"Maintains lvl1 charge on the missile launcher.",
	"Nemesis Codes",
	"Maintains max charge on the nemesis.",
	"Maintains lvl3 charge on the nemesis.",
	"Maintains lvl2 charge on the nemesis.",
	"Maintains lvl1 charge on the nemesis.",
	"Polar Star Codes",
	"Maintains max charge on the polar star.",
	"Maintains lvl3 charge on the polar star.",
	"Maintains lvl2 charge on the polar star.",
	"Maintains lvl1 charge on the polar star.",
	"Snake Codes",
	"Maintains max charge on the snake.",
	"Maintains lvl3 charge on the snake.",
	"Maintains lvl2 charge on the snake.",
	"Maintains lvl1 charge on the snake.",
	"Spur Codes",
	"Maintains max charge on the spur.",
	"Maintains lvl3 charge on the spur.",
	"Maintains lvl2 charge on the spur.",
	"Maintains lvl1 charge on the spur.",
	"Miscellaneous Codes",
	"Increases player movement speed.",
	"Keeps your air maxed.",
	"Keeps your booster fuel maxed.\n\nBooster v0.8 sound and particles won't occur.",
	"Allows you to jump infinitely.\n\nYou cannot use the booster with this code on!",
	"HP does not exceed 1, missiles do not exceed 0, only blade and nemesis charge.\n\nWhy would you pick this?!?",
};

#endif